#!/bin/bash
# Web Automation Suite - 运行入口

echo "Web Automation Suite"
echo "==================="
echo ""
echo "请进入scripts目录运行："
echo ""
echo "  Chrome CDP连接："
echo "    cd scripts"
echo "    node cdp-connect.js"
echo ""
echo "  表单自动化："
echo "    cd scripts"
echo "    node form-automation.js"
echo ""
echo "  定时任务："
echo "    cd scripts"
echo "    node scheduled-task.js"
echo ""
echo "详细说明请查看 README.md"
echo ""
echo "注意：请先启动Chrome远程调试："
echo "  chrome.exe --remote-debugging-port=9222"
